[package]
name   	= "sycamore_learning"
version	= "0.1.0"
edition	= "2021"

# See more keys and their definitions at doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sycamore = "0.8.0-beta.7"
